-- MySQL Script generated by MySQL Workbench
-- 08/19/15 21:55:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema adeies_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adeies_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adeies_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `adeies_db` ;

-- -----------------------------------------------------
-- Table `adeies_db`.`geniki_dieuthinsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`geniki_dieuthinsi` (
  `genikidid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `gdname` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`genikidid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adeies_db`.`dieuthinsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`dieuthinsi` (
  `dieuthinsiid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `dname` VARCHAR(255) NULL COMMENT '',
  `genikidid` INT NULL COMMENT '',
  PRIMARY KEY (`dieuthinsiid`)  COMMENT '',
  INDEX `gdid_idx` (`genikidid` ASC)  COMMENT '',
  CONSTRAINT `gdid_fk`
    FOREIGN KEY (`genikidid`)
    REFERENCES `adeies_db`.`geniki_dieuthinsi` (`genikidid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adeies_db`.`tmima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`tmima` (
  `tmimaid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tmname` VARCHAR(255) NULL COMMENT '',
  `dieuthinsiid` INT NULL COMMENT '',
  PRIMARY KEY (`tmimaid`)  COMMENT '',
  INDEX `did_idx` (`dieuthinsiid` ASC)  COMMENT '',
  CONSTRAINT `did_fk`
    FOREIGN KEY (`dieuthinsiid`)
    REFERENCES `adeies_db`.`dieuthinsi` (`dieuthinsiid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `adeies_db`.`idiotites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`idiotites` (
  `ididiotita_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idname` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`ididiotita_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adeies_db`.`ypallhlos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`ypallhlos` (
  `ypallhlosid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `genikidid` INT NULL COMMENT '',
  `dieuthinsiid` INT NULL COMMENT '',
  `tmimaid` INT NULL COMMENT '',
  `onoma` VARCHAR(255) NULL COMMENT '',
  `epitheto` VARCHAR(255) NULL COMMENT '',
  `max_adeies` VARCHAR(255) NULL COMMENT '',
  `fylo` BINARY(1) NULL COMMENT '',
  `idiotita_id` INT NULL COMMENT '',
  `ypoloipo_adeion_trexon` INT NULL COMMENT '',
  `ypoloipo_adeion_palio` INT NULL COMMENT '',
  PRIMARY KEY (`ypallhlosid`)  COMMENT '',
  INDEX `gdid_idx` (`genikidid` ASC)  COMMENT '',
  INDEX `did_idx` (`dieuthinsiid` ASC)  COMMENT '',
  INDEX `tmid_idx` (`tmimaid` ASC)  COMMENT '',
  INDEX `idiotita_id_idx` (`idiotita_id` ASC)  COMMENT '',
  CONSTRAINT `gdid_fk`
    FOREIGN KEY (`genikidid`)
    REFERENCES `adeies_db`.`geniki_dieuthinsi` (`genikidid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `did_fk`
    FOREIGN KEY (`dieuthinsiid`)
    REFERENCES `adeies_db`.`dieuthinsi` (`dieuthinsiid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tmid_fk`
    FOREIGN KEY (`tmimaid`)
    REFERENCES `adeies_db`.`tmima` (`tmimaid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idiotita_id_fk`
    FOREIGN KEY (`idiotita_id`)
    REFERENCES `adeies_db`.`idiotites` (`ididiotita_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adeies_db`.`typos_adeias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`typos_adeias` (
  `typos_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `typosname` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`typos_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adeies_db`.`katastash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`katastash` (
  `katastasi_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `katname` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`katastasi_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adeies_db`.`adeies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`adeies` (
  `adeia_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ypallhlosid` INT NULL COMMENT '',
  `typos_id` INT NULL COMMENT '',
  `date_submitted` DATETIME NULL COMMENT '',
  `date_starts` DATETIME NULL COMMENT '',
  `date_ends` DATETIME NULL COMMENT '',
  `ar_adeiwn` INT NULL COMMENT '',
  `katastasi_id` INT NULL COMMENT '',
  `yp_dieuthinti` BINARY(1) NULL COMMENT '',
  `yp_proistamenou` BINARY(1) NULL COMMENT '',
  `yp_gen_dieuthinti` BINARY(1) NULL COMMENT '',
  `yp_ektelestikou` BINARY(1) NULL COMMENT '',
  `yp_perifereiarxh` BINARY(1) NULL COMMENT '',
  PRIMARY KEY (`adeia_id`)  COMMENT '',
  INDEX `ypid_idx` (`ypallhlosid` ASC)  COMMENT '',
  INDEX `typos_id_idx` (`typos_id` ASC)  COMMENT '',
  INDEX `kat_id_idx` (`katastasi_id` ASC)  COMMENT '',
  CONSTRAINT `ypid_fk`
    FOREIGN KEY (`ypallhlosid`)
    REFERENCES `adeies_db`.`ypallhlos` (`ypallhlosid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `typos_id_fk`
    FOREIGN KEY (`typos_id`)
    REFERENCES `adeies_db`.`typos_adeias` (`typos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `kat_id_fk`
    FOREIGN KEY (`katastasi_id`)
    REFERENCES `adeies_db`.`katastash` (`katastasi_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adeies_db`.`paidia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adeies_db`.`paidia` (
  `paidiid` INT NOT NULL COMMENT '',
  `ypallhlosid` INT NULL COMMENT '',
  `ilikia` INT NULL COMMENT '',
  PRIMARY KEY (`paidiid`)  COMMENT '',
  INDEX `ypid_idx` (`ypallhlosid` ASC)  COMMENT '',
  CONSTRAINT `ypid_fk2`
    FOREIGN KEY (`ypallhlosid`)
    REFERENCES `adeies_db`.`ypallhlos` (`ypallhlosid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
